### ISSUE TITLE
[Bug] Glowmaps that are not layer0 in an item model do not render.

### ISSUE THREAD

**Issue by BunkWire2X8** [Chisel-Team/ConnectedTexturesMod#113]
Due to this unfortunate issue, the only way to make an item glow is to add the glowmap to the first layer, cut holes in the original texture, and then add it to the second layer. Example is depicted below.
![totem layers](https://user-images.githubusercontent.com/44177200/68738931-74c00600-059c-11ea-9b35-6c54df60ecff.png)

**Comment by tterrag1098** [comment]
I believe this was caused by CTM getting confused with layers and item models. It could sometimes reorder quads even when no layer was explicitly set, and cause quads to be emitted multiple times (since the action for "no layer" was to emit all quads for all layers - and quads with no layer exist in all layers).

I've changed the CTM parser (technically a breaking change but I doubt it will really affect anyone) to default to `null` instead of SOLID layer, meaning item texture metadata can emulate vanilla textures by leaving out the field. I've also made sure that CTM models return only distinct quads, and for good measure added some caching to the generation of those distinct lists.
