### ISSUE TITLE
Mekanism and Immersive Engineering Connected Textures are pink

### ISSUE THREAD

**Issue by LazyDope** [Chisel-Team/ConnectedTexturesMod#43]
Connected textures for blocks like the Thermal Evaporation Blocks, Dynamic Tank blocks or Steel Scaffolding are pink when CTM is installed with Chisel and Optifine

With just CTM, CTM and Chisel or CTM and Optifine
![2018-03-10_12 38 47](https://user-images.githubusercontent.com/27651460/37297702-b25037b2-25f4-11e8-979a-4324fa23d02f.png)

With all Three
![2018-03-10_12 37 12](https://user-images.githubusercontent.com/27651460/37297906-470f464a-25f5-11e8-8ae3-5199d795fa71.png)

CTM Ver: 1.12-0.2.3.12
Optifine Ver: 1.12.2_HD_U_C9
Chisel Ver: 1.12.2-0.2.0.31

**Comment by ChloeDawn** [comment]
Does this happen whenever you run the game and open the world? Or only after reloading resources (e.g changing a resource pack) in-game?

**Comment by LazyDope** [comment]
When I open the world, It may have something to do with other mods, but I'm not sure what it could be, as  those were the mods that seems to change textures when they were added or removed, I can give a full mod list if needed.

**Comment by LazyDope** [comment]
The Textures are all default, no resource packs

**Comment by LazyDope** [comment]
Chisel textures are fine
![image](https://user-images.githubusercontent.com/27651460/37299067-9eed6182-25f8-11e8-8b79-2ab04f8e4c32.png)

**Comment by tterrag1098** [comment]
Can you show your log? Do you get any texture errors? cc @aidancbrady

**Comment by LazyDope** [comment]
[Here](https://pastebin.com/GrxDZ4wH) is the most recent forge log

Edit: Pastebin missed all the errors in the paste

**Comment by tterrag1098** [comment]
That doesn't seem like the right log, the Forge log should show a summary of missing textures at the end.

**Comment by LazyDope** [comment]
what should the log be named? I just sent "latest.txt" under the logs folder. Did you check the updated log? As when I pasted it the first time the errors weren't included

**Comment by LazyDope** [comment]
[Here](https://pastebin.com/GrxDZ4wH) is the updated log again

**Comment by tterrag1098** [comment]
Try the fml-client-latest.log

**Comment by LazyDope** [comment]
[Tada](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1821239/fml-client-latest.log)

**Comment by tterrag1098** [comment]
I see tons of errors from "TexFix" can you try without it?

**Comment by LazyDope** [comment]
I actually added TexFix after this happened, but I'll see what I can do

**Comment by LazyDope** [comment]
As expected, that's a negative, but [here's](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1821267/fml-client-latest.log) a new log either way

**Comment by tterrag1098** [comment]
So to be clear, this doesn't happen with just CTM+Optifine+Mekanism ?

**Comment by LazyDope** [comment]
Ok, so with the log I sent just before, it doesn't require a texture reload to cause the problem, but with just CTM, Chisel and Optifine it does.

**Comment by LazyDope** [comment]
[CTM, Optifine, Mek Log](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1821295/fml-client-latest.log)

**Comment by LazyDope** [comment]
I don't know what other mod could be causing the non-reload change

**Comment by xAlicatt** [comment]
Last I checked, we are having this issue in https://minecraft.curseforge.com/projects/jakspack and we are NOT running Optifine.

Edit: Just loaded up and checked and yes, still having this issue and we are not running optifine.
https://imgur.com/a/IzTKzx0

**Comment by tterrag1098** [comment]
This only happens after reloading resources ingame?

**Comment by xAlicatt** [comment]
This happened on a freshly started client. Iirc, I tested it before both with and without resource pack, but I can test again later if you like...it takes a while to load my pack.

**Comment by tterrag1098** [comment]
This is a known issue when reloading resources but I haven't seen it
happening without that. Can you confirm that it happens without other mods
installed?

**Comment by xAlicatt** [comment]
Hasn't someone already confirmed that it doesn't? Obviously it's a conflict with another mod...but, respectfully, nobody runs only these mods. And just because it is a conflict with another mod, doesn't mean, again respectfully, that it's not your mod causing the issue, at the very least indirectly. I may not be a dev, but I've been doing this long enough to know that much. 

I don't have the time or the desire to test over 250 mods to see which one it is, I just had a complaint from a player of my pack asking about texture issues and did what most people do...tried to narrow down the potential causes based on process of elimination....found threads talking about similar issues...shared my personal findings in said threads. 

I don't honestly think I have any other mods in my pack that mess with multiblock/connected textures...so I wouldn't really know where to start looking anyway.

**Comment by xAlicatt** [comment]
https://i.imgur.com/UML5LVQ.png

This is my pack in it's most recent version, with the only thing missing being Chisel and Connected Textures.

**Comment by xAlicatt** [comment]
Just further info here, the mod versions in my pack: 
-Forge is ver 2655
-Chisel 0.2.0.31
-CTM 0.2.3.12
-Mek 9.4.3.330

I just loaded it up with only Chisel missing and these are the results...seems to be CTM causing the problem based on this:
https://imgur.com/a/LNFTdjV

**Comment by thiakil** [comment]
> I don't have the time or the desire to test over 250 mods to see which one it is

Honestly that's quite disrespectful. It is *your* combination of mods. Expecting someone else to find the culprit mod is just lazy - we are busy too.

You can start by searching your `fml-client-latest.log` for `Examining for coremod candidacy` and try without coremods. Failing that you will need to start removing mods one by one until the error stops (I'd suggest starting with mods that do *any* special rendering) or doing the inverse and start from a non-bugged world and add mods until it happens.

**Comment by xAlicatt** [comment]
@thiakil  I removed CTM and the error stopped immediately, as stated above. Also since I posted last, there is at least one connected texture with this same issue in the new Thaumcraft Beta for 1.12. 

When I stated I don't have the time or the desire, that's literally what I meant. I don't expect someone else to do it, I'm just stating I cannot and will not test over 250 mods for compatibility. It takes like 15-20 minutes to load up the pack. Imagine doing that (potentially) over 250 times.

Removing CTM makes the issue go away. My conclusion from that is that CTM is what's causing the issue...either directly or indirectly.

**Comment by thiakil** [comment]
> My conclusion from that is that CTM is what's causing the issue...either directly or indirectly.

That conclusion is flawed, as it has been mentioned (by yourself in fact) that it doesn't occur with just CTM and the affected mod(s). Correlation is not causation. Another mod is interfering with CTM.

> Imagine doing that (potentially) over 250 times.

I don't recall saying it would be pleasant. But you do you, deal without CTM for all it matters to us.

**Comment by tterrag1098** [comment]
Some massive miscommunication going on in this thread.

@xAlicatt Mekanism *uses* CTM to create its connected textures on those blocks. So obviously removing CTM will solve the issue, because once you do so they are normal models...

**Comment by xAlicatt** [comment]
Seems to be Barkifier. https://minecraft.curseforge.com/projects/barkifier?gameCategorySlug=mc-mods&projectID=253042

I started out with your mods + some that I thought might cause the problem, then when that didn't show the error, I started at the top of the list on the main pack and added those mods to the test pack in groups of 5. When the error went away, I removed the mods from the last grouping 1 by one until the error went away. Then when Barkifier was shown to be a likely culprit, I tried removing Barkifier from the main pack and the error is gone. I've reported to them, and now I'm reporting here, since it's potentially a conflict specifically between your mod and their mod.

**Comment by Tollainmear** [comment]
Not only mekanism's multi-block structure but also effect the `transparent reactor casing` of nuclearcraft.
![ctmissue](https://user-images.githubusercontent.com/25898067/39753553-d98e97d6-52f1-11e8-9f79-2aeb4a04eeb0.png)

**Comment by VioletWyvern** [comment]
Same problem here, Tested in some mods and some connect textures was showing as purple missing textures

<a href="https://imgur.com/xP7dXJr"><img src="https://i.imgur.com/xP7dXJr.png" title="source: imgur.com" /></a>

Tested mods (will have missing texture):

ImmersiveEngineering
Mekanism
TwilightForest
Techguns
Vic's Modern Warfare

**Comment by ThePuzzlemaker** [comment]
In 1.12.2, with the below versions, the problem seems to be fixed.
CTM: MC1.12-0.2.3.12
Chisel: MC1.12.2-0.2.0.31
Mekanism (Core, Tools, and Generators): 1.12.2-9.4.10.345
Optifine: 1.12.2_HD_U_D3

**Comment by kencinder** [comment]
I'm running the same versions as ThePuzzlemaker and with or without Optifine present, the issue persists. Changing Mip-Map levels alters how the issue appears, but off <-> 4 and it very much still appears.

I did NOT have this issue before moving from Forge 2611 to 2655 however, with all the same mod versions in play.

**Comment by xAlicatt** [comment]
@kencinder And you're not running Barkifier?

**Comment by kencinder** [comment]
@xAlicatt No I am not, I suppose I should have listed all my mods.

https://pastebin.com/ZQ8CH2tm

I added Baubles/Thaumcraft when moving from 2611 to 2655...aside from that, nothing new IIRC

**Comment by tterrag1098** [comment]
This seems to be unrelated to Mekanism or any other mod, and is simply the same as #54. Tracking this under #54 as the issue is more clearly stated there.
