### ISSUE TITLE
Animations and CTM

### ISSUE THREAD

**Issue by seancrain** [Chisel-Team/ConnectedTexturesMod#73]
I am in the process of converting the animations for Sphax PureBDcraft from using OptiFine to using CTM due to OptiFine's modpack rules.

The redstone textures for Sphax PureBDcraft have both connected textures and animations, and I want to know if there is a way to utilize those animations within a connected texture system, with the top left having an animation, the top right, etc.

Is this supported, and if so, what do I need to do?

**Comment by ChloeDawn** [comment]
CTM does support animations, yes. The `ctm` tag can be defined alongside the `animation` tag. Information can be found [here](https://github.com/Chisel-Team/ConnectedTexturesMod/wiki/CTM-into-Texture-Metadata). However, OptiFine is not your only issue here. You overlooked the terms of use for Sphax's PureBDCraft, which disallows redistribution and/or modification of the resourcepack. The full terms of use can be found in the download section [here](https://bdcraft.net/downloads/purebdcraft-minecraft/#download).

If your pack is truly private, I'm sure you can come to a resolution at your own discretion, but I personally do not condone redistribution of content that prohibits it in the terms of use, private or otherwise.

**Comment by seancrain** [comment]
I didn’t overlook it, I made a forum post asking about it before I did anything: I had a discussion about this with HanFox, the lead moderator of the BDcraft forum, and what he said was this:

—Quote—

I think this is actually a "fuzzy" edge case.

The Terms state you can't take textures to make a remix pack (which would generally be considered a pack that's strictly intended to change the look of Minecraft in general), whereas the modpack rules state you can use assets for mod patches where the general effect is the same.

As the CTM mod isn't a sweeping change, but rather adding support taking textures from the main pack to make the CTM mod work is okay as long as it remains as a separate small patch (like other mod patches).

Another reason why it should be okay to make a patch is, quite simply, we'll never support a mod like that in the main pack. There's no guarantee of it's longevity, and it's more work for little gain as not everyone who plays modded moves on to the newer MC versions (in fact, as far as modded go, the player base diminishes constantly as people stick to older versions).

So, if you want to make a mod patch for the CTM mod: please do and please release it on the forum for everyone else ;)

—End Quote—

Thank you for linking me the file on how to support it. What I actually need to know is how to lay out the texture file. Do I put the whole left animation on the top left or do I break up the animations (all 4 frame 1, all 4 frame 2, etc)

**Comment by ChloeDawn** [comment]
Ah, I see, my bad. Nice to see Han is slack about that. You can find an example of an animated CTM texture in my repository [here](https://github.com/SleeplessDevelopment/Glazed/tree/shards/src/main/resources/assets/glazed/textures/blocks/glass/energetic). And there is documentation for the standard CTM format on the old CTM repository [here](https://github.com/Chisel-Team/CTMLib/wiki/Standard-CTM-Format).

**Comment by tterrag1098** [comment]
The entire CTM map is still treated by the game as a single "texture" thus you just animate the entire thing as normal and it "just works"
